##
## Makefile for Cardboard_Pulley in /cygdrive/c/Users/Habi/Documents/ETNA/C/Cardboard_Pulley
## 
## Made by HABI Açal
## Login   <habi_a@etna-alternance.net>
## 
## Started on  Thu Jan 25 21:45:31 2018 HABI Açal
## Last update Thu Jan 25 22:26:03 2018 HABI Açal
##
MAKE	=	make

all	:
		$(MAKE) -C etape1 all
		$(MAKE) -C etape2 all
		$(MAKE) -C etape3 all

clean	:
		$(MAKE) -C etape1 clean 
		$(MAKE) -C etape2 clean
		$(MAKE) -C etape3 clean

fclean	:
		$(MAKE) -C etape1 fclean
		$(MAKE) -C etape2 fclean
		$(MAKE) -C etape3 fclean

re	:
		$(MAKE) -C etape1 re
		$(MAKE) -C etape2 re
		$(MAKE) -C etape3 re

.PHONY	:
		$(MAKE) -C etape1 .PHONY
		$(MAKE) -C etape2 .PHONY
		$(MAKE) -C etape3 .PHONY
